spring:
  datasource:
    url: jdbc:mysql://localhost/vending-db
    username: user
    password: pwd
  jpa.hibernate.ddl-auto: update

application.jwt:
  secretKey: securesecuresecuresecuresecuresecuresecuresecuresecuresecuresecure
  tokenPrefix: Bearer
  tokenExpirationAfterDays: 10

